# Config generated by xxdns agent. DO NOT EDIT.
# source: acls.tpl
{{range .}}
#default (date_created: {{ .CreateTime }}   date_updated: {{ .UpdateTime}} )
include "/etc/named/acls/{{ .ISP }}.acl";
{{- end }}