// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/acls": {
            "get": {
                "description": "Get all ACLs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Acl"
                ],
                "summary": "Get all ACLs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pagesize",
                        "name": "pagesize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pagenum",
                        "name": "pagenum",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Acl"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a acl",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Acl"
                ],
                "summary": "Create a acl",
                "parameters": [
                    {
                        "description": "填写ACL信息",
                        "name": "AclInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.Acl"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "comment": {
                                            "type": "string"
                                        },
                                        "disabled": {
                                            "type": "boolean"
                                        },
                                        "filter": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Acl"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/acls/{id}": {
            "get": {
                "description": "Get acl by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Acl"
                ],
                "summary": "Get acl by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "acl id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Acl"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Create a acl",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Acl"
                ],
                "summary": "Create a acl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "填写Acl信息",
                        "name": "aclInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.aclCreateForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "comment": {
                                            "type": "string"
                                        },
                                        "disabled": {
                                            "type": "boolean"
                                        },
                                        "name": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Acl"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Get acl by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Acl"
                ],
                "summary": "Get acl by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{error:{code:400,message:\"bad request\"}}",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "404": {
                        "description": "{error:{code:404,message:\"record not found\"}}",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "{error:{code:404,message:\"server error\"}}",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/domains": {
            "get": {
                "description": "Get all domains",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Domain"
                ],
                "summary": "Get all domains",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pagesize",
                        "name": "pagesize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pagenum",
                        "name": "pagenum",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Domain"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a domain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Domain"
                ],
                "summary": "Create a domain",
                "parameters": [
                    {
                        "description": "填写域名信息",
                        "name": "domainInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.domainCreateForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "comment": {
                                            "type": "string"
                                        },
                                        "disabled": {
                                            "type": "boolean"
                                        },
                                        "name": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Domain"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/domains/{id}": {
            "get": {
                "description": "Get domain by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Domain"
                ],
                "summary": "Get domain by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "domain id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Domain"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Create a domain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Domain"
                ],
                "summary": "Create a domain",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "填写域名信息",
                        "name": "domainInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.domainCreateForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "comment": {
                                            "type": "string"
                                        },
                                        "disabled": {
                                            "type": "boolean"
                                        },
                                        "name": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Domain"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Get domain by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Domain"
                ],
                "summary": "Get domain by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{error:{code:400,message:\"bad request\"}}",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "404": {
                        "description": "{error:{code:404,message:\"record not found\"}}",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "{error:{code:404,message:\"server error\"}}",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ipdb": {
            "get": {
                "description": "Get all IPDB",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPDB"
                ],
                "summary": "Get all IPDB",
                "parameters": [
                    {
                        "type": "string",
                        "description": "country",
                        "name": "country",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "province",
                        "name": "province",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "isp",
                        "name": "isp",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pagesize",
                        "name": "pagesize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pagenum",
                        "name": "pagenum",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.IPDB"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a ipdb",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPDB"
                ],
                "summary": "Create a ipdb",
                "parameters": [
                    {
                        "description": "填写ip信息",
                        "name": "IPDBInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.IPDB"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.IPDB"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/records": {
            "get": {
                "description": "Get all records",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "Get all records",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pagesize",
                        "name": "pagesize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pagenum",
                        "name": "pagenum",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Record"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "Create a record",
                "parameters": [
                    {
                        "description": "填写视图信息",
                        "name": "RecordInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.recordCreateForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "comment": {
                                            "type": "string"
                                        },
                                        "content": {
                                            "type": "string"
                                        },
                                        "disabled": {
                                            "type": "boolean"
                                        },
                                        "domain": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "type": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Record"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/records/{id}": {
            "get": {
                "description": "Get record by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "Get record by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "record id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Record"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Create a record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "Create a record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "填写视图信息",
                        "name": "RecordInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.recordCreateForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "comment": {
                                            "type": "string"
                                        },
                                        "content": {
                                            "type": "string"
                                        },
                                        "disabled": {
                                            "type": "boolean"
                                        },
                                        "domain": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "type": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Record"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Get record by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "Get record by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{error:{code:400,message:\"bad request\"}}",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "404": {
                        "description": "{error:{code:404,message:\"record not found\"}}",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "{error:{code:404,message:\"server error\"}}",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/views": {
            "get": {
                "description": "Get all views",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "View"
                ],
                "summary": "Get all views",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pagesize",
                        "name": "pagesize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pagenum",
                        "name": "pagenum",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.View"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a view",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "View"
                ],
                "summary": "Create a view",
                "parameters": [
                    {
                        "description": "填写视图信息",
                        "name": "viewInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.viewCreateForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "comment": {
                                            "type": "string"
                                        },
                                        "disabled": {
                                            "type": "boolean"
                                        },
                                        "name": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.View"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/views/{id}": {
            "get": {
                "description": "Get view by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "View"
                ],
                "summary": "Get view by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "view id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.View"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Create a view",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "View"
                ],
                "summary": "Create a view",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "填写视图信息",
                        "name": "viewInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.viewCreateForm"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "comment": {
                                            "type": "string"
                                        },
                                        "disabled": {
                                            "type": "boolean"
                                        },
                                        "name": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.View"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Get view by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "View"
                ],
                "summary": "Get view by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{error:{code:400,message:\"bad request\"}}",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "404": {
                        "description": "{error:{code:404,message:\"record not found\"}}",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    },
                    "500": {
                        "description": "{error:{code:404,message:\"server error\"}}",
                        "schema": {
                            "$ref": "#/definitions/controllers.errResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Get health status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Get health status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.healthResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.healthResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        },
                                        "status": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.aclCreateForm": {
            "type": "object",
            "required": [
                "name",
                "path"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "controllers.domainCreateForm": {
            "type": "object",
            "required": [
                "contract",
                "disabled",
                "expire",
                "name",
                "provider",
                "refresh",
                "retry",
                "serial",
                "ttl",
                "type"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "contract": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "expire": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "refresh": {
                    "type": "integer"
                },
                "retry": {
                    "type": "integer"
                },
                "serial": {
                    "type": "integer"
                },
                "ttl": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "controllers.errResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "controllers.healthResponse": {
            "type": "object"
        },
        "controllers.recordCreateForm": {
            "type": "object",
            "required": [
                "content",
                "domain",
                "name",
                "ttl",
                "type",
                "view"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "domain": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "ttl": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "view": {
                    "type": "string"
                }
            }
        },
        "controllers.viewCreateForm": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Acl": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "filter": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Domain": {
            "type": "object",
            "required": [
                "comment",
                "contract",
                "expire",
                "mininum",
                "name",
                "provider",
                "refresh",
                "retry",
                "serial",
                "ttl",
                "type"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "contract": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "expire": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "mininum": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "refresh": {
                    "type": "integer"
                },
                "retry": {
                    "type": "integer"
                },
                "serial": {
                    "type": "integer"
                },
                "ttl": {
                    "type": "integer"
                },
                "type": {
                    "description": "master,slave,hit,forward",
                    "type": "string"
                }
            }
        },
        "models.IPDB": {
            "type": "object",
            "properties": {
                "cidr": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isp": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                }
            }
        },
        "models.Record": {
            "type": "object",
            "required": [
                "content",
                "domain",
                "name",
                "ttl",
                "type",
                "view"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "domain": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "ttl": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "view": {
                    "type": "string"
                }
            }
        },
        "models.View": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "acls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Acl"
                    }
                },
                "comment": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
