definitions:
  controllers.errResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  controllers.healthResponse:
    type: object
  controllers.viewCreateForm:
    properties:
      comment:
        type: string
      disabled:
        type: boolean
      name:
        type: string
    required:
    - comment
    - name
    type: object
  controllers.viewObject:
    properties:
      comment:
        type: string
      disabled:
        type: boolean
      id:
        type: integer
      name:
        type: string
    required:
    - comment
    - name
    type: object
  models.View:
    properties:
      comment:
        type: string
      disabled:
        type: boolean
      id:
        type: integer
      name:
        type: string
    required:
    - comment
    - name
    type: object
info:
  contact: {}
paths:
  /api/v1/views:
    get:
      consumes:
      - application/json
      description: Get all views
      parameters:
      - description: pagesize
        in: query
        name: pagesize
        type: string
      - description: pagenum
        in: query
        name: pagenum
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.View'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.errResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errResponse'
      summary: Get all views
      tags:
      - View
    post:
      consumes:
      - application/json
      description: Create a views
      parameters:
      - description: 填写视图信息
        in: body
        name: viewInfo
        required: true
        schema:
          allOf:
          - $ref: '#/definitions/controllers.viewCreateForm'
          - properties:
              comment:
                type: string
              disabled:
                type: boolean
              name:
                type: string
            type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.viewObject'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controllers.errResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errResponse'
      summary: Create a views
      tags:
      - View
  /healthz:
    get:
      consumes:
      - application/json
      description: Get health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.healthResponse'
            - properties:
                status:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/controllers.healthResponse'
            - properties:
                error:
                  type: string
                status:
                  type: string
              type: object
      summary: Get health status
      tags:
      - Health
swagger: "2.0"
